language: php

php:
    - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit

matrix:
  include:
    - php: 7.1.13
    - php: 7.2
